import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


const APP_NAME = "Aung Zaw Phyo";
const APP_DEFAULT_TITLE = "Aung Zaw Phyo";
const APP_TITLE_TEMPLATE = "%s";
const APP_DESCRIPTION = "Aung Zaw Phyo | Web Developer";
const APP_URL = process.env.NEXT_PUBLIC_URL;

export const metadata = {
  metadataBase: new URL(APP_URL),
  applicationName: APP_NAME,
  title: {
    default: APP_DEFAULT_TITLE,
    template: APP_TITLE_TEMPLATE,
  },
  description: APP_DESCRIPTION,
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: APP_DEFAULT_TITLE,
    // startUpImage: [],
  },
  formatDetection: {
    telephone: false,
  },
  openGraph: {
    type: "website",
    siteName: APP_NAME,
    title: {
      default: APP_DEFAULT_TITLE,
      template: APP_TITLE_TEMPLATE,
    },
    description: APP_DESCRIPTION,
  },
  twitter: {
    card: "summary",
    title: {
      default: APP_DEFAULT_TITLE,
      template: APP_TITLE_TEMPLATE,
    },
    description: APP_DESCRIPTION,
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
          <meta charSet="utf-8" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="apple-touch-icon" sizes="180x180" href="/favicon.ico" />
          <link rel="icon" type="image/png" sizes="32x32" href="/favicon.ico" />
          <link rel="icon" type="image/png" sizes="16x16" href="/favicon.ico" />
          <link rel="manifest" href="/manifest.json" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta name="theme-color" content="#000000" />
          <meta name="aungzawphyo portfolio" content="web developer PHP developer JavaScript Laravel React" />
          

          <meta property="og:title" content="Aung Zaw Phyo | Web Developer" />
          <meta property="og:type" content="Portfolio" />
          <meta property="og:image" content="/me3.jpg" />
          <meta property="og:url" content="https://aungzawphyo.com/" />
          <meta name="twitter:card" content="Web Developer | Javascrip and PHP" />

          <title>Aung Zaw Phyo</title>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
